name: Enforce PRs from Dev to Main

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  enforce_dev_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR base and head branches
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
            echo "error: Only PRs from 'dev' branch to 'main' branch are allowed."
            exit 1
          fi
