name: Log Commits to File

on:
  push:
    branches:
      - main
    branches-ignore:
      - dev

jobs:
  log_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check if commits.log exists
        run: |
          if [[ ! -f "commits.log" ]]; then
            touch commits.log
          fi

      - name: Log Commits
        run: |
          echo "--------------------" >> commits.log
          echo "Commit ID: ${GITHUB_SHA}" >> commits.log
          echo "Commit author: ${GITHUB_ACTOR}" >> commits.log
          echo "Commit date and time: $(date -u)" >> commits.log
          echo "Commit message:" >> commits.log
          echo "${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}" >> commits.log
          echo "" >> commits.log
          echo "" >> commits.log
