name: Code Quality
on:
  #Will check code quality for any push or pulls
  push: {}
  workflow_dispatch:
jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "lts/*"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run code analysis
        run: npm run lint #This is what is used to actually run check

      - name: Run audit check
      - run: npm audit #This checks for security vulnerabilities
